### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [fszatkowski/Audio-Enhancement-with-Deep-Learning#1]
Hi there, 1st of all thanks for this cool work !

Since we've "doxed" it in our [HyMPS project](https://forart.it/HyMPS/) (under the [AUDIO category](https://github.com/FORARTfe/HyMPS#-) \ [AI-based page](https://github.com/FORARTfe/HyMPS/blob/main/Audio/AI-based.md#--) \ [Enhancements subsection](https://github.com/FORARTfe/HyMPS/blob/main/Audio/AI-based.md#enhancements-)), can you please add a GH-compliant license file ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may _sounds_ like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/fszatkowski/Audio-Enhancement-with-Deep-Learning)
(badge-generator URL: https://badgen.net/github/license/fszatkowski/Audio-Enhancement-with-Deep-Learning)

Anyway you can easily set a standard one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by fszatkowski** [comment]
Hi, its nice to see my work is useful for you, I added MIT license to the
repository.
Regards,
Filip

wt., 7 maj 2024 o 09:24 F.O.R.A.R.T. npo ***@***.***>
napisał(a):

**Comment by MarcoRavich** [comment]
Works now, thanks !
